# Task1

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("sendy_logistics.csv")
df = df.head(100)
df

,Order No,User Id,Vehicle Type,Platform Type,Personal or Business,Placement - Day of Month,Placement - Weekday (Mo = 1),Placement - Time,Confirmation - Day of Month,Confirmation - Weekday (Mo = 1),...,Arrival at Destination - Time,Distance (KM),Temperature,Precipitation in millimeters,Pickup Lat,Pickup Long,Destination Lat,Destination Long,Rider Id,Time from Pickup to Arrival
0,Order_No_4211,User_Id_633,Bike,3,Business,9,5,9:35:46 AM,9,5,...,10:39:55 AM,4,20.4,NaN,-1.317755,36.830370,-1.300406,36.829741,Rider_Id_432,745
1,Order_No_25375,User_Id_2285,Bike,3,Personal,12,5,11:16:16 AM,12,5,...,12:17:22 PM,16,26.4,NaN,-1.351453,36.899315,-1.295004,36.814358,Rider_Id_856,1993
2,Order_No_1899,User_Id_265,Bike,3,Business,30,2,12:39:25 PM,30,2,...,1:00:38 PM,3,NaN,NaN,-1.308284,36.843419,-1.300921,36.828195,Rider_Id_155,455
3,Order_No_9336,User_Id_1402,Bike,3,Business,15,5,9:25:34 AM,15,5,...,10:05:27 AM,9,19.2,NaN,-1.281301,36.832396,-1.257147,36.795063,Rider_Id_855,1341
4,Order_No_27883,User_Id_1737,Bike,1,Personal,13,1,9:55:18 AM,13,1,...,10:25:37 AM,9,15.4,NaN,-1.266597,36.792118,-1.295041,36.809817,Rider_Id_770,1214
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Order_No_13979,User_Id_1578,Bike,3,Business,5,1,3:20:54 PM,5,1,...,4:13:36 PM,5,25.8,NaN,-1.288780,36.816831,-1.259753,36.806629,Rider_Id_795,1487
96,Order_No_14861,User_Id_1187,Bike,1,Personal,17,1,10:40:49 AM,17,1,...,11:48:04 AM,4,25.2,NaN,-1.302596,36.861444,-1.330287,36.854286,Rider_Id_810,1694
97,Order_No_18800,User_Id_1329,Bike,3,Business,13,1,3:18:01 PM,13,1,...,3:59:04 PM,6,NaN,NaN,-1.273056,36.811298,-1.237063,36.798196,Rider_Id_161,1307
98,Order_No_26616,User_Id_2523,Bike,3,Business,13,1,9:13:15 AM,13,1,...,10:03:34 AM,20,NaN,NaN,-1.255189,36.782203,-1.325125,36.899593,Rider_Id_190,2621
99,Order_No_20962,User_Id_3544,Bike,2,Personal,18,5,6:52:38 PM,18,5,...,8:21:28 PM,4,19.3,NaN,-1.255370,36.775600,-1.271377,36.788429,Rider_Id_103,1196

In [3]:
import requests

def get_current_temp(lat,long):
    
    api_key = "bea34a996c8eb297edf4f2a22fe5bb91"
    lat = str(lat)
    lon = str(long)
    url = "https://api.openweathermap.org/data/2.5/onecall?lat=%s&lon=%s&appid=%s&units=metric" % (lat, lon, api_key)

    response = requests.get(url)
    data = response.json()
    return data['current']['temp']

df['Temp_Diff'] = df['Temperature'] - df.apply(lambda x: get_current_temp(x['Destination Lat'], x['Destination Long']), axis=1)
df

,Order No,User Id,Vehicle Type,Platform Type,Personal or Business,Placement - Day of Month,Placement - Weekday (Mo = 1),Placement - Time,Confirmation - Day of Month,Confirmation - Weekday (Mo = 1),...,Distance (KM),Temperature,Precipitation in millimeters,Pickup Lat,Pickup Long,Destination Lat,Destination Long,Rider Id,Time from Pickup to Arrival,Temp_Diff
0,Order_No_4211,User_Id_633,Bike,3,Business,9,5,9:35:46 AM,9,5,...,4,20.4,NaN,-1.317755,36.830370,-1.300406,36.829741,Rider_Id_432,745,3.06
1,Order_No_25375,User_Id_2285,Bike,3,Personal,12,5,11:16:16 AM,12,5,...,16,26.4,NaN,-1.351453,36.899315,-1.295004,36.814358,Rider_Id_856,1993,9.45
2,Order_No_1899,User_Id_265,Bike,3,Business,30,2,12:39:25 PM,30,2,...,3,NaN,NaN,-1.308284,36.843419,-1.300921,36.828195,Rider_Id_155,455,NaN
3,Order_No_9336,User_Id_1402,Bike,3,Business,15,5,9:25:34 AM,15,5,...,9,19.2,NaN,-1.281301,36.832396,-1.257147,36.795063,Rider_Id_855,1341,2.30
4,Order_No_27883,User_Id_1737,Bike,1,Personal,13,1,9:55:18 AM,13,1,...,9,15.4,NaN,-1.266597,36.792118,-1.295041,36.809817,Rider_Id_770,1214,-1.55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Order_No_13979,User_Id_1578,Bike,3,Business,5,1,3:20:54 PM,5,1,...,5,25.8,NaN,-1.288780,36.816831,-1.259753,36.806629,Rider_Id_795,1487,8.76
96,Order_No_14861,User_Id_1187,Bike,1,Personal,17,1,10:40:49 AM,17,1,...,4,25.2,NaN,-1.302596,36.861444,-1.330287,36.854286,Rider_Id_810,1694,7.75
97,Order_No_18800,User_Id_1329,Bike,3,Business,13,1,3:18:01 PM,13,1,...,6,NaN,NaN,-1.273056,36.811298,-1.237063,36.798196,Rider_Id_161,1307,NaN
98,Order_No_26616,User_Id_2523,Bike,3,Business,13,1,9:13:15 AM,13,1,...,20,NaN,NaN,-1.255189,36.782203,-1.325125,36.899593,Rider_Id_190,2621,NaN
99,Order_No_20962,User_Id_3544,Bike,2,Personal,18,5,6:52:38 PM,18,5,...,4,19.3,NaN,-1.255370,36.775600,-1.271377,36.788429,Rider_Id_103,1196,2.43

In [4]:
df['Fehr_Temp4'] = df['Temperature'].apply(lambda x: (x * (9/5)) + 32)
df

,Order No,User Id,Vehicle Type,Platform Type,Personal or Business,Placement - Day of Month,Placement - Weekday (Mo = 1),Placement - Time,Confirmation - Day of Month,Confirmation - Weekday (Mo = 1),...,Temperature,Precipitation in millimeters,Pickup Lat,Pickup Long,Destination Lat,Destination Long,Rider Id,Time from Pickup to Arrival,Temp_Diff,Fehr_Temp4
0,Order_No_4211,User_Id_633,Bike,3,Business,9,5,9:35:46 AM,9,5,...,20.4,NaN,-1.317755,36.830370,-1.300406,36.829741,Rider_Id_432,745,3.06,68.72
1,Order_No_25375,User_Id_2285,Bike,3,Personal,12,5,11:16:16 AM,12,5,...,26.4,NaN,-1.351453,36.899315,-1.295004,36.814358,Rider_Id_856,1993,9.45,79.52
2,Order_No_1899,User_Id_265,Bike,3,Business,30,2,12:39:25 PM,30,2,...,NaN,NaN,-1.308284,36.843419,-1.300921,36.828195,Rider_Id_155,455,NaN,NaN
3,Order_No_9336,User_Id_1402,Bike,3,Business,15,5,9:25:34 AM,15,5,...,19.2,NaN,-1.281301,36.832396,-1.257147,36.795063,Rider_Id_855,1341,2.30,66.56
4,Order_No_27883,User_Id_1737,Bike,1,Personal,13,1,9:55:18 AM,13,1,...,15.4,NaN,-1.266597,36.792118,-1.295041,36.809817,Rider_Id_770,1214,-1.55,59.72
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Order_No_13979,User_Id_1578,Bike,3,Business,5,1,3:20:54 PM,5,1,...,25.8,NaN,-1.288780,36.816831,-1.259753,36.806629,Rider_Id_795,1487,8.76,78.44
96,Order_No_14861,User_Id_1187,Bike,1,Personal,17,1,10:40:49 AM,17,1,...,25.2,NaN,-1.302596,36.861444,-1.330287,36.854286,Rider_Id_810,1694,7.75,77.36
97,Order_No_18800,User_Id_1329,Bike,3,Business,13,1,3:18:01 PM,13,1,...,NaN,NaN,-1.273056,36.811298,-1.237063,36.798196,Rider_Id_161,1307,NaN,NaN
98,Order_No_26616,User_Id_2523,Bike,3,Business,13,1,9:13:15 AM,13,1,...,NaN,NaN,-1.255189,36.782203,-1.325125,36.899593,Rider_Id_190,2621,NaN,NaN
99,Order_No_20962,User_Id_3544,Bike,2,Personal,18,5,6:52:38 PM,18,5,...,19.3,NaN,-1.255370,36.775600,-1.271377,36.788429,Rider_Id_103,1196,2.43,66.74

# Task 2

In [5]:
df = pd.read_csv("ufo.csv")
df = df.head(100)
df

,City,Colors Reported,Shape Reported,State,Time
0,Ithaca,NaN,TRIANGLE,NY,6/1/1930 22:00
1,Willingboro,NaN,OTHER,NJ,6/30/1930 20:00
2,Holyoke,NaN,OVAL,CO,2/15/1931 14:00
3,Abilene,NaN,DISK,KS,6/1/1931 13:00
4,New York Worlds Fair,NaN,LIGHT,NY,4/18/1933 19:00
...,...,...,...,...,...
95,Ojai,NaN,LIGHT,CA,7/15/1948 22:00
96,New York City,NaN,CIRCLE,NY,8/1/1948 2:00
97,Conshohocken,NaN,OVAL,PA,8/15/1948 12:00
98,Sharpsburg,NaN,CIRCLE,MD,12/12/1948 23:30
99,Seattle,NaN,DISK,WA,4/10/1949 15:00

In [6]:
df['Time'] = pd.to_datetime(df["Time"])

In [7]:
df['IN_December'] = (df['Time'].dt.month).apply(lambda x: x == 12)
df

,City,Colors Reported,Shape Reported,State,Time,IN_December
0,Ithaca,NaN,TRIANGLE,NY,1930-06-01 22:00:00,False
1,Willingboro,NaN,OTHER,NJ,1930-06-30 20:00:00,False
2,Holyoke,NaN,OVAL,CO,1931-02-15 14:00:00,False
3,Abilene,NaN,DISK,KS,1931-06-01 13:00:00,False
4,New York Worlds Fair,NaN,LIGHT,NY,1933-04-18 19:00:00,False
...,...,...,...,...,...,...
95,Ojai,NaN,LIGHT,CA,1948-07-15 22:00:00,False
96,New York City,NaN,CIRCLE,NY,1948-08-01 02:00:00,False
97,Conshohocken,NaN,OVAL,PA,1948-08-15 12:00:00,False
98,Sharpsburg,NaN,CIRCLE,MD,1948-12-12 23:30:00,True
99,Seattle,NaN,DISK,WA,1949-04-10 15:00:00,False

In [8]:
import datetime
from dateutil.relativedelta import relativedelta

WW1 = datetime.datetime(1914, 7, 28)
df['Time_Diff_From_WW1'] = df['Time'].apply(lambda x: relativedelta(x, WW1).years) 
df

,City,Colors Reported,Shape Reported,State,Time,IN_December,Time_Diff_From_WW1
0,Ithaca,NaN,TRIANGLE,NY,1930-06-01 22:00:00,False,15
1,Willingboro,NaN,OTHER,NJ,1930-06-30 20:00:00,False,15
2,Holyoke,NaN,OVAL,CO,1931-02-15 14:00:00,False,16
3,Abilene,NaN,DISK,KS,1931-06-01 13:00:00,False,16
4,New York Worlds Fair,NaN,LIGHT,NY,1933-04-18 19:00:00,False,18
...,...,...,...,...,...,...,...
95,Ojai,NaN,LIGHT,CA,1948-07-15 22:00:00,False,33
96,New York City,NaN,CIRCLE,NY,1948-08-01 02:00:00,False,34
97,Conshohocken,NaN,OVAL,PA,1948-08-15 12:00:00,False,34
98,Sharpsburg,NaN,CIRCLE,MD,1948-12-12 23:30:00,True,34
99,Seattle,NaN,DISK,WA,1949-04-10 15:00:00,False,34

# Task3

In [9]:
df = pd.read_csv("visitor-interests.csv")
df = df.head(50)
df

,IP,UserAgent,Country,Languages,Interests
0,1.10.195.126,Mozilla/5.0 (Windows NT 6.1; Win64; x64) Apple...,TH,english,other
1,1.1.217.211,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,TH,thai,blog/personal homepage
2,1.115.198.107,Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.3...,JP,english,shop/online shopping website
3,1.121.152.143,Mozilla/5.0 (Linux; Android 7.0; Nexus 9 Build...,AU,english,company
4,1.123.135.213,Mozilla/5.0 (iPad; CPU OS 9_3_5 like Mac OS X)...,AU,english,company
5,1.124.48.210,Mozilla/5.0 (Linux; Android 5.0; SAMSUNG SM-G9...,AU,english,company
6,1.124.48.99,Mozilla/5.0 (Linux; Android 5.0; SAMSUNG SM-G9...,AU,english,company
7,1.126.48.118,Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7....,AU,english,company
8,1.126.48.171,Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; ...,AU,english,company
9,1.126.48.47,Mozilla/5.0 (iPhone; CPU iPhone OS 7_0_4 like ...,AU,english,company
10,1.128.96.235,Mozilla/5.0 (Linux; Android 6.0.1; SAMSUNG SM-...,AU,english,shop/online shopping website
11,1.128.96.30,Mozilla/5.0 (iPhone; CPU iPhone OS 8_1_3 like ...,AU,english,company
12,1.128.97.122,Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_3 like ...,AU,english,company
13,1.129.96.120,Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_5 like ...,AU,english,company
14,1.129.96.21,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6...,AU,english,church
15,1.129.96.252,Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_5 like ...,AU,english,shop/online shopping website
16,1.129.96.79,Mozilla/5.0 (Linux; Android 6.0.1; SAMSUNG SM-...,AU,english,company
17,1.129.96.86,Mozilla/5.0 (Linux; Android 6.0.1; SM-N915G Bu...,AU,english,company
18,1.129.97.46,Mozilla/5.0 (Linux; U; Android 4.2.2; en-au; S...,AU,english,company
19,1.129.97.62,Mozilla/5.0 (Windows NT 6.3; WOW64; rv:48.0) G...,AU,english,blog/personal homepage
20,1.132.96.125,Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_4 like ...,AU,english,company
21,1.132.96.203,Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_1 like ...,AU,english,company
22,1.132.97.60,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,AU,english,company
23,1.136.97.40,Mozilla/5.0 (iPhone; CPU iPhone OS 9_2 like Ma...,AU,english,company
24,1.136.97.67,Mozilla/5.0 (Linux; Android 5.1.1; SAMSUNG SM-...,AU,english,company
25,1.144.96.234,Mozilla/5.0 (iPad; CPU OS 9_3_5 like Mac OS X)...,AU,english,company
26,1.144.96.77,Mozilla/5.0 (iPhone; CPU iPhone OS 9_2 like Ma...,AU,english,company
27,1.144.97.41,Mozilla/5.0 (Linux; Android 6.0.1; SAMSUNG SM-...,AU,english,company
28,1.152.96.14,Mozilla/5.0 (iPad; CPU OS 8_4 like Mac OS X) A...,AU,english,company/other
29,1.152.96.156,Mozilla/5.0 (Windows NT 6.1; WOW64; rv:48.0) G...,AU,english,company
30,1.152.96.251,Mozilla/5.0 (Linux; Android 6.0.1; SM-N910G Bu...,AU,english,company
31,1.152.97.102,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,AU,english,sport organization
32,1.152.97.25,Mozilla/5.0 (iPhone; CPU iPhone OS 9_2_1 like ...,AU,english,company
33,1.161.13.16,Mozilla/5.0 (Linux; Android 4.3; ASUS_T00I Bui...,TW,english,company
34,1.161.27.235,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,TW,english,company/other
35,1.162.51.164,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,TW,english,blog/personal homepage
36,1.163.208.88,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,TW,chinese,social network/forum
37,1.164.141.85,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,TW,chinese,social network/forum
38,1.164.73.87,Mozilla/5.0 (Windows NT 10.0; WOW64; rv:48.0) ...,TW,english,shop/online shopping website
39,1.168.54.202,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,TW,english,other
40,1.173.31.228,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.3...,TW,english,company
41,1.186.37.87,Mozilla/5.0 (Linux; U; Android 6.0; en-US; Len...,IN,english,social network/forum
42,1.186.38.82,Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.3...,IN,english,company
43,1.186.98.212,Mozilla/5.0 (Linux; Android 5.1.1; SM-J500F Bu...,IN,english,shop/online shopping website
44,1.187.118.90,Mozilla/5.0 (Linux; U; Android 5.1.1; en-in; R...,IN,english,company
45,1.187.188.80,Mozilla/5.0 (Linux; U; Android 4.2.2; en-us; A...,IN,english,company
46,1.187.196.224,Mozilla/5.0 (Linux; Android 4.1.2; GT-S7262 Bu...,IN,hindi,news website
47,1.187.201.169,Mozilla/5.0 (Linux; U; Android 5.1; en-US; viv...,IN,english,educational institution
48,1.187.207.245,Mozilla/5.0 (Linux; U; Android 5.0.2; en-US; L...,IN,english,company
49,1.187.58.245,Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_5 like ...,IN,english,company/other

In [10]:
import user_agents

def extract_web_data(ua):
    ua = user_agents.parse(ua)
    return pd.Series((ua.browser.family, ua.os.family, ua.device.family))
df[['Browser', 'OS', 'Device']] = df['UserAgent'].apply(extract_web_data)
df

,IP,UserAgent,Country,Languages,Interests,Browser,OS,Device
0,1.10.195.126,Mozilla/5.0 (Windows NT 6.1; Win64; x64) Apple...,TH,english,other,Chrome,Windows,Other
1,1.1.217.211,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,TH,thai,blog/personal homepage,Chrome,Windows,Other
2,1.115.198.107,Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.3...,JP,english,shop/online shopping website,Chrome,Windows,Other
3,1.121.152.143,Mozilla/5.0 (Linux; Android 7.0; Nexus 9 Build...,AU,english,company,Chrome,Android,Nexus 9
4,1.123.135.213,Mozilla/5.0 (iPad; CPU OS 9_3_5 like Mac OS X)...,AU,english,company,Mobile Safari,iOS,iPad
5,1.124.48.210,Mozilla/5.0 (Linux; Android 5.0; SAMSUNG SM-G9...,AU,english,company,Samsung Internet,Android,Samsung SM-G900I
6,1.124.48.99,Mozilla/5.0 (Linux; Android 5.0; SAMSUNG SM-G9...,AU,english,company,Samsung Internet,Android,Samsung SM-G900I
7,1.126.48.118,Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7....,AU,english,company,IE,Windows,Other
8,1.126.48.171,Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; ...,AU,english,company,Firefox,Mac OS X,Mac
9,1.126.48.47,Mozilla/5.0 (iPhone; CPU iPhone OS 7_0_4 like ...,AU,english,company,Mobile Safari,iOS,iPhone
10,1.128.96.235,Mozilla/5.0 (Linux; Android 6.0.1; SAMSUNG SM-...,AU,english,shop/online shopping website,Samsung Internet,Android,Samsung SM-G900I
11,1.128.96.30,Mozilla/5.0 (iPhone; CPU iPhone OS 8_1_3 like ...,AU,english,company,Mobile Safari,iOS,iPhone
12,1.128.97.122,Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_3 like ...,AU,english,company,Mobile Safari,iOS,iPhone
13,1.129.96.120,Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_5 like ...,AU,english,company,Mobile Safari,iOS,iPhone
14,1.129.96.21,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6...,AU,english,church,Chrome,Mac OS X,Mac
15,1.129.96.252,Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_5 like ...,AU,english,shop/online shopping website,Google,iOS,iPhone
16,1.129.96.79,Mozilla/5.0 (Linux; Android 6.0.1; SAMSUNG SM-...,AU,english,company,Samsung Internet,Android,Samsung SM-T355Y
17,1.129.96.86,Mozilla/5.0 (Linux; Android 6.0.1; SM-N915G Bu...,AU,english,company,Chrome Mobile,Android,Samsung SM-N915G
18,1.129.97.46,Mozilla/5.0 (Linux; U; Android 4.2.2; en-au; S...,AU,english,company,Android,Android,Samsung SM-T315
19,1.129.97.62,Mozilla/5.0 (Windows NT 6.3; WOW64; rv:48.0) G...,AU,english,blog/personal homepage,Firefox,Windows,Other
20,1.132.96.125,Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_4 like ...,AU,english,company,Mobile Safari,iOS,iPhone
21,1.132.96.203,Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_1 like ...,AU,english,company,Mobile Safari,iOS,iPhone
22,1.132.97.60,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,AU,english,company,Chrome,Windows,Other
23,1.136.97.40,Mozilla/5.0 (iPhone; CPU iPhone OS 9_2 like Ma...,AU,english,company,Mobile Safari,iOS,iPhone
24,1.136.97.67,Mozilla/5.0 (Linux; Android 5.1.1; SAMSUNG SM-...,AU,english,company,Samsung Internet,Android,Samsung SM-G800Y
25,1.144.96.234,Mozilla/5.0 (iPad; CPU OS 9_3_5 like Mac OS X)...,AU,english,company,Mobile Safari,iOS,iPad
26,1.144.96.77,Mozilla/5.0 (iPhone; CPU iPhone OS 9_2 like Ma...,AU,english,company,Mobile Safari,iOS,iPhone
27,1.144.97.41,Mozilla/5.0 (Linux; Android 6.0.1; SAMSUNG SM-...,AU,english,company,Samsung Internet,Android,Samsung SM-N920I
28,1.152.96.14,Mozilla/5.0 (iPad; CPU OS 8_4 like Mac OS X) A...,AU,english,company/other,Mobile Safari,iOS,iPad
29,1.152.96.156,Mozilla/5.0 (Windows NT 6.1; WOW64; rv:48.0) G...,AU,english,company,Firefox,Windows,Other
30,1.152.96.251,Mozilla/5.0 (Linux; Android 6.0.1; SM-N910G Bu...,AU,english,company,Chrome Mobile,Android,Samsung SM-N910G
31,1.152.97.102,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,AU,english,sport organization,Chrome,Windows,Other
32,1.152.97.25,Mozilla/5.0 (iPhone; CPU iPhone OS 9_2_1 like ...,AU,english,company,Mobile Safari,iOS,iPhone
33,1.161.13.16,Mozilla/5.0 (Linux; Android 4.3; ASUS_T00I Bui...,TW,english,company,Chrome Mobile,Android,Asus T00I
34,1.161.27.235,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,TW,english,company/other,Chrome,Windows,Other
35,1.162.51.164,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,TW,english,blog/personal homepage,Chromium,Ubuntu,Other
36,1.163.208.88,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,TW,chinese,social network/forum,Chrome,Windows,Other
37,1.164.141.85,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,TW,chinese,social network/forum,Dragon,Windows,Other
38,1.164.73.87,Mozilla/5.0 (Windows NT 10.0; WOW64; rv:48.0) ...,TW,english,shop/online shopping website,Firefox,Windows,Other
39,1.168.54.202,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,TW,english,other,Chrome,Windows,Other
40,1.173.31.228,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.3...,TW,english,company,Chrome,Windows,Other
41,1.186.37.87,Mozilla/5.0 (Linux; U; Android 6.0; en-US; Len...,IN,english,social network/forum,UC Browser,Android,Lenovo A7000-a
42,1.186.38.82,Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.3...,IN,english,company,Chrome,Windows,Other
43,1.186.98.212,Mozilla/5.0 (Linux; Android 5.1.1; SM-J500F Bu...,IN,english,shop/online shopping website,Chrome Mobile,Android,Samsung SM-J500F
44,1.187.118.90,Mozilla/5.0 (Linux; U; Android 5.1.1; en-in; R...,IN,english,company,MiuiBrowser,Android,XiaoMi Redmi Note 3
45,1.187.188.80,Mozilla/5.0 (Linux; U; Android 4.2.2; en-us; A...,IN,english,company,Android,Android,A550s IPS
46,1.187.196.224,Mozilla/5.0 (Linux; Android 4.1.2; GT-S7262 Bu...,IN,hindi,news website,Chrome Mobile,Android,Samsung GT-S7262
47,1.187.201.169,Mozilla/5.0 (Linux; U; Android 5.1; en-US; viv...,IN,english,educational institution,UC Browser,Android,vivo Y15S
48,1.187.207.245,Mozilla/5.0 (Linux; U; Android 5.0.2; en-US; L...,IN,english,company,UC Browser,Android,Lenovo A6010
49,1.187.58.245,Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_5 like ...,IN,english,company/other,Mobile Safari,iOS,iPhone

In [11]:
import requests
import json

def get_lat_long(ip):
    response = requests.get("https://geolocation-db.com/jsonp/" + ip)
    result = response.content.decode()
    result = result.split("(")[1].strip(")")
    result = json.loads(result)
    return pd.Series((result['latitude'], result['longitude']))

df[['Latitude', 'Longitude']] = df['IP'].apply(get_lat_long)
df

,IP,UserAgent,Country,Languages,Interests,Browser,OS,Device,Latitude,Longitude
0,1.10.195.126,Mozilla/5.0 (Windows NT 6.1; Win64; x64) Apple...,TH,english,other,Chrome,Windows,Other,13.7667,100.6500
1,1.1.217.211,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,TH,thai,blog/personal homepage,Chrome,Windows,Other,15.0555,102.2148
2,1.115.198.107,Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.3...,JP,english,shop/online shopping website,Chrome,Windows,Other,35.6600,139.8067
3,1.121.152.143,Mozilla/5.0 (Linux; Android 7.0; Nexus 9 Build...,AU,english,company,Chrome,Android,Nexus 9,-33.4940,143.2104
4,1.123.135.213,Mozilla/5.0 (iPad; CPU OS 9_3_5 like Mac OS X)...,AU,english,company,Mobile Safari,iOS,iPad,-34.9287,138.5986
5,1.124.48.210,Mozilla/5.0 (Linux; Android 5.0; SAMSUNG SM-G9...,AU,english,company,Samsung Internet,Android,Samsung SM-G900I,-33.4940,143.2104
6,1.124.48.99,Mozilla/5.0 (Linux; Android 5.0; SAMSUNG SM-G9...,AU,english,company,Samsung Internet,Android,Samsung SM-G900I,-33.4940,143.2104
7,1.126.48.118,Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7....,AU,english,company,IE,Windows,Other,-35.0031,117.8660
8,1.126.48.171,Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; ...,AU,english,company,Firefox,Mac OS X,Mac,-35.0031,117.8660
9,1.126.48.47,Mozilla/5.0 (iPhone; CPU iPhone OS 7_0_4 like ...,AU,english,company,Mobile Safari,iOS,iPhone,-35.0031,117.8660
10,1.128.96.235,Mozilla/5.0 (Linux; Android 6.0.1; SAMSUNG SM-...,AU,english,shop/online shopping website,Samsung Internet,Android,Samsung SM-G900I,-26.8588,152.9614
11,1.128.96.30,Mozilla/5.0 (iPhone; CPU iPhone OS 8_1_3 like ...,AU,english,company,Mobile Safari,iOS,iPhone,-26.8588,152.9614
12,1.128.97.122,Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_3 like ...,AU,english,company,Mobile Safari,iOS,iPhone,-28.0278,153.4334
13,1.129.96.120,Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_5 like ...,AU,english,company,Mobile Safari,iOS,iPhone,-32.0077,151.9633
14,1.129.96.21,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6...,AU,english,church,Chrome,Mac OS X,Mac,-32.0077,151.9633
15,1.129.96.252,Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_5 like ...,AU,english,shop/online shopping website,Google,iOS,iPhone,-32.0077,151.9633
16,1.129.96.79,Mozilla/5.0 (Linux; Android 6.0.1; SAMSUNG SM-...,AU,english,company,Samsung Internet,Android,Samsung SM-T355Y,-32.0077,151.9633
17,1.129.96.86,Mozilla/5.0 (Linux; Android 6.0.1; SM-N915G Bu...,AU,english,company,Chrome Mobile,Android,Samsung SM-N915G,-32.0077,151.9633
18,1.129.97.46,Mozilla/5.0 (Linux; U; Android 4.2.2; en-au; S...,AU,english,company,Android,Android,Samsung SM-T315,-33.8778,151.2435
19,1.129.97.62,Mozilla/5.0 (Windows NT 6.3; WOW64; rv:48.0) G...,AU,english,blog/personal homepage,Firefox,Windows,Other,-33.8778,151.2435
20,1.132.96.125,Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_4 like ...,AU,english,company,Mobile Safari,iOS,iPhone,-33.4940,143.2104
21,1.132.96.203,Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_1 like ...,AU,english,company,Mobile Safari,iOS,iPhone,-33.4940,143.2104
22,1.132.97.60,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,AU,english,company,Chrome,Windows,Other,-33.4940,143.2104
23,1.136.97.40,Mozilla/5.0 (iPhone; CPU iPhone OS 9_2 like Ma...,AU,english,company,Mobile Safari,iOS,iPhone,-37.8103,144.9544
24,1.136.97.67,Mozilla/5.0 (Linux; Android 5.1.1; SAMSUNG SM-...,AU,english,company,Samsung Internet,Android,Samsung SM-G800Y,-37.8103,144.9544
25,1.144.96.234,Mozilla/5.0 (iPad; CPU OS 9_3_5 like Mac OS X)...,AU,english,company,Mobile Safari,iOS,iPad,-33.8000,151.1833
26,1.144.96.77,Mozilla/5.0 (iPhone; CPU iPhone OS 9_2 like Ma...,AU,english,company,Mobile Safari,iOS,iPhone,-33.8000,151.1833
27,1.144.97.41,Mozilla/5.0 (Linux; Android 6.0.1; SAMSUNG SM-...,AU,english,company,Samsung Internet,Android,Samsung SM-N920I,-33.8000,151.1833
28,1.152.96.14,Mozilla/5.0 (iPad; CPU OS 8_4 like Mac OS X) A...,AU,english,company/other,Mobile Safari,iOS,iPad,-37.7204,145.0698
29,1.152.96.156,Mozilla/5.0 (Windows NT 6.1; WOW64; rv:48.0) G...,AU,english,company,Firefox,Windows,Other,-37.7204,145.0698
30,1.152.96.251,Mozilla/5.0 (Linux; Android 6.0.1; SM-N910G Bu...,AU,english,company,Chrome Mobile,Android,Samsung SM-N910G,-37.7204,145.0698
31,1.152.97.102,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,AU,english,sport organization,Chrome,Windows,Other,-37.7204,145.0698
32,1.152.97.25,Mozilla/5.0 (iPhone; CPU iPhone OS 9_2_1 like ...,AU,english,company,Mobile Safari,iOS,iPhone,-37.7204,145.0698
33,1.161.13.16,Mozilla/5.0 (Linux; Android 4.3; ASUS_T00I Bui...,TW,english,company,Chrome Mobile,Android,Asus T00I,25.0478,121.5318
34,1.161.27.235,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,TW,english,company/other,Chrome,Windows,Other,25.0478,121.5318
35,1.162.51.164,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,TW,english,blog/personal homepage,Chromium,Ubuntu,Other,25.0478,121.5318
36,1.163.208.88,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,TW,chinese,social network/forum,Chrome,Windows,Other,25.0478,121.5318
37,1.164.141.85,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,TW,chinese,social network/forum,Dragon,Windows,Other,25.0478,121.5318
38,1.164.73.87,Mozilla/5.0 (Windows NT 10.0; WOW64; rv:48.0) ...,TW,english,shop/online shopping website,Firefox,Windows,Other,25.0478,121.5318
39,1.168.54.202,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,TW,english,other,Chrome,Windows,Other,24.1469,120.6839
40,1.173.31.228,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.3...,TW,english,company,Chrome,Windows,Other,22.6163,120.3133
41,1.186.37.87,Mozilla/5.0 (Linux; U; Android 6.0; en-US; Len...,IN,english,social network/forum,UC Browser,Android,Lenovo A7000-a,18.9750,72.8258
42,1.186.38.82,Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.3...,IN,english,company,Chrome,Windows,Other,18.9750,72.8258
43,1.186.98.212,Mozilla/5.0 (Linux; Android 5.1.1; SM-J500F Bu...,IN,english,shop/online shopping website,Chrome Mobile,Android,Samsung SM-J500F,22.5697,88.3697
44,1.187.118.90,Mozilla/5.0 (Linux; U; Android 5.1.1; en-in; R...,IN,english,company,MiuiBrowser,Android,XiaoMi Redmi Note 3,28.6000,77.2000
45,1.187.188.80,Mozilla/5.0 (Linux; U; Android 4.2.2; en-us; A...,IN,english,company,Android,Android,A550s IPS,22.5697,88.3697
46,1.187.196.224,Mozilla/5.0 (Linux; Android 4.1.2; GT-S7262 Bu...,IN,hindi,news website,Chrome Mobile,Android,Samsung GT-S7262,32.7333,74.8667
47,1.187.201.169,Mozilla/5.0 (Linux; U; Android 5.1; en-US; viv...,IN,english,educational institution,UC Browser,Android,vivo Y15S,32.7333,74.8667
48,1.187.207.245,Mozilla/5.0 (Linux; U; Android 5.0.2; en-US; L...,IN,english,company,UC Browser,Android,Lenovo A6010,32.7333,74.8667
49,1.187.58.245,Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_5 like ...,IN,english,company/other,Mobile Safari,iOS,iPhone,20.0000,77.0000